### ISSUE TITLE
Can you add to your readme how this is different than the AngularJS for Brackets extension from AngularUI?

### ISSUE THREAD

**Issue by caboosesw** [sirajc/Brackets-AngularJS-CodeHints#4]
Thx

**Comment by stamminator** [comment]
Bump.

**Comment by sirajc** [comment]
@caboosesw Angular UI's extension is for Javascript, this is for html

**Comment by sirajc** [comment]
Added screenshots in Readme, this might help to know about this extension

**Comment by caboosesw** [comment]
... then why do you name your AngularJS-Codehints ... since coliff's is HTML5CodeHints?

**Comment by caboosesw** [comment]
Or are you saying you extended one based on HTML with Angular ... and  the other extended a JS one with Angular? I think that is what you are saying.

**Comment by sirajc** [comment]
Precisely, My plan was to send PR to coliff's repo, but then folks not using angular will get ng hints and that would be wrong, hence Angular Code hints
