### ISSUE TITLE
Not seeing any code hints

### ISSUE THREAD

**Issue by stamminator** [sirajc/Brackets-AngularJS-CodeHints#5]
Using Brackets 1.4.0-16380, I have this extension installed, but am not seeing any code hints, even when  clicking Ctrl+Space. Here are some examples:

![screenshot 5](https://cloud.githubusercontent.com/assets/10633170/10212478/f1082b32-67cd-11e5-939a-90c4a98f30d1.png)
![screenshot 7](https://cloud.githubusercontent.com/assets/10633170/10212541/dd6b3c44-67ce-11e5-888e-8fd9ecf2f9c1.png)

Here are the extensions I have installed in case you need them for troubleshooting:
![screenshot 8](https://cloud.githubusercontent.com/assets/10633170/10212586/65a4f3e8-67cf-11e5-83e9-925ea94283ab.png)

Thank in advance.

**Comment by mariani-public** [comment]
I'm encountering the same issue as stamminator mentioned above.  I'm also running Brackets version 1.4.0-16380.  I did not attach screenshots, as they would show the same behavior as stamminator posted.

**Comment by sirajc** [comment]
@stamminator Thanks for the details, This extension was not compatible with recent versions of Brackets, Have updated the repo with changes done by coliff on parent stream. Angular attributes are working now. Fixed in 0b6b628fe388b586ce1f63eadeeef0feed88988e
