### ISSUE TITLE
Installation fails on Brackets Release 1.8 build 1.8.0-17108 

### ISSUE THREAD

**Issue by rafael-yure** [sirajc/Brackets-AngularJS-CodeHints#8]
Hi,

Installation is failing on Release 1.8 build 1.8.0-17108 of Brackets with message:

![image](https://cloud.githubusercontent.com/assets/8876325/22858136/d3ed58d0-f09b-11e6-8776-0c9153e4792c.png)

**Comment by sirajc** [comment]
Can you check if you facing the similar issue with `Brackets-HTML5CodeHints`

**Comment by rafael-yure** [comment]
Sorry it took so long.

I was facing the exact same problem with Brackets-HTML5CodeHints.

I removed brackets and installed again; now it's working. 

Thank you for the fast response.
